export const DEPARTMENT_REGISTER_REQUEST = 'DEPARTMENT_REGISTER_REQUEST';
export const DEPARTMENT_REGISTER_SUCCESS = 'DEPARTMENT_REGISTER_SUCCESS';
export const DEPARTMENT_REGISTER_FAIL = 'DEPARTMENT_REGISTER_FAIL';

export const DEPARTMENT_DETAILS_REQUEST = 'DEPARTMENT_DETAILS_REQUEST';
export const DEPARTMENT_DETAILS_SUCCESS = 'DEPARTMENT_DETAILS_SUCCESS';
export const DEPARTMENT_DETAILS_FAIL = 'DEPARTMENT_DETAILS_FAIL';
export const DEPARTMENT_DETAILS_RESET = 'DEPARTMENT_DETAILS_RESET';

export const DEPARTMENT_LIST_REQUEST = 'DEPARTMENT_LIST_REQUEST';
export const DEPARTMENT_LIST_SUCCESS = 'DEPARTMENT_LIST_SUCCESS';
export const DEPARTMENT_LIST_FAIL = 'DEPARTMENT_LIST_FAIL';
export const DEPARTMENT_LIST_RESET = 'DEPARTMENT_LIST_RESET';

export const DEPARTMENT_LIST_FILTER_REQUEST = 'DEPARTMENT_LIST_FILTER_REQUEST';
export const DEPARTMENT_LIST_FILTER_SUCCESS = 'DEPARTMENT_LIST_FILTER_SUCCESS';
export const DEPARTMENT_LIST_FILTER_FAIL = 'DEPARTMENT_LIST_FILTER_FAIL';
export const DEPARTMENT_LIST_FILTER_RESET = 'DEPARTMENT_LIST_FILTER_RESET';

export const DEPARTMENT_UPDATE_REQUEST = 'DEPARTMENT_UPDATE_REQUEST';
export const DEPARTMENT_UPDATE_SUCCESS = 'DEPARTMENT_UPDATE_SUCCESS';
export const DEPARTMENT_UPDATE_FAIL = 'DEPARTMENT_UPDATE_FAIL';
export const DEPARTMENT_UPDATE_RESET = 'DEPARTMENT_UPDATE_RESET';
